baseurl         = "https://marxinal-projects.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Portofolio"
  subtitle    = "Jelena Kalinic"

  cover       = "backgrounddots.jpeg"
  description = "Hello there! Here you will find more about who am I as well as my projects and ongoing research!"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  githubName = "marxinal"

  author = "Jelena Kalinic"
  authorAvatar = "id.jpg"
  authorLocation = "Amsterdam, NL"
  authorWebsite = "https://github.com/marxinal/Projects"
  authorDescription = "Behavioural Data Scientist"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "About me"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Projects"
  url = "/tags/projects/"
  weight = 100

[[menu.main]]
  name = "Hobbies"
  url = "/categories/hobbies/"
  weight = 99

[[menu.main]]
  name = "Other"
  url = "https://google.com/"
  weight = 95



